server {
    listen 5173; # Timeweb App Platform / Docker Compose expects port 5173 or we can change it to 80.
    # Keep 5173 for consistency with previous setup.
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}