"""Add company and project fields

Revision ID: 46e1d475c964
Revises: e9d392ad1204
Create Date: 2026-03-12 11:30:35.257298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46e1d475c964'
down_revision: Union[str, Sequence[str], None] = 'e9d392ad1204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('ogrn', sa.String(length=15), nullable=True))
    op.add_column('companies', sa.Column('sro_build', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('sro_project', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_companies_ogrn'), 'companies', ['ogrn'], unique=True)
    op.add_column('projects', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('projects', sa.Column('general_contractor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'companies', ['general_contractor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'general_contractor_id')
    op.drop_column('projects', 'address')
    op.drop_index(op.f('ix_companies_ogrn'), table_name='companies')
    op.drop_column('companies', 'sro_project')
    op.drop_column('companies', 'sro_build')
    op.drop_column('companies', 'ogrn')
    # ### end Alembic commands ###
