FROM python:3.11-slim

WORKDIR /app

# Копируем файл с зависимостями
COPY requirements.txt .

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Устанавливаем gunicorn для production
RUN pip install --no-cache-dir gunicorn uvicorn[standard]

# Копируем исходный код
COPY . .

# Запускаем FastAPI через gunicorn с воркерами uvicorn
CMD ["gunicorn", "main:app", "-w", "2", "-k", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8001"]